name: ansible
adopt-info: ansible
summary: Ansible is a radically simple IT automation system.
description: |
    Ansible is a radically simple IT automation system. 
    It handles configuration-management, application deployment, cloud provisioning, 
    ad-hoc task-execution, and multinode orchestration -- including trivializing things 
    like zero-downtime rolling updates with load balancers.
    
grade: stable 
confinement: strict
base: core20

package-repositories:
 - type: apt
   ppa: deadsnakes/ppa

plugs:
  ansible:
    interface: personal-files
    write:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
    read:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
  ansible:
    interface: personal-files
    read:
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
  ansible:
    interface: personal-files
    read:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT       
    write:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT      

apps:
  ansible:
    command: bin/ansible
  ansible-config:
    command: bin/ansible-config
  ansible-console:
    command: bin/ansible-console
  ansible-doc:
    command: bin/ansible-doc
  ansible-galaxy:
    command: bin/ansible-galaxy
  ansible-inventory:
    command: bin/ansible-inventory
  ansible-playbook:
    command: bin/ansible-playbook
  ansible-pull:
    command: bin/ansible-pull
  ansible-test:
    command: bin/ansible-test
  ansible-vault:
    command: bin/ansible-vault
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - mount-observe
      - system-files
      - personal-files
     
parts: 
  ansible:
    source: https://github.com/ansible/ansible
    source-type: git
    source-branch: stable-2.14
    plugin: python
    requirements: [requirements.txt]
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - python3.12
      - software-properties-common
      
    stage-packages:
      - python3.12
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography
      - python3-jmespath
