name: ansible
adopt-info: ansible
summary: Ansible is a radically simple IT automation system.
description: |
    Ansible is a radically simple IT automation system. 
    It handles configuration-management, application deployment, cloud provisioning, 
    ad-hoc task-execution, and multinode orchestration -- including trivializing things 
    like zero-downtime rolling updates with load balancers.
    
grade: stable 
confinement: classic
base: core20

package-repositories:
 - type: apt
   ppa: deadsnakes/ppa

apps:
ansible: 
  command: usr/bin/ansible
     
parts: 
  ansible:
    source: https://github.com/ansible/ansible
    source-type: git
    source-branch: stable-2.14
    plugin: python
    requirements: [requirements.txt]
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - python3.10
      - software-properties-common
      
    stage-packages:
      - python3.10
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography
      - python3-jmespath
