name: ansible
adopt-info: ansible
summary: Ansible is a radically simple IT automation system.
description: |
    Ansible is a radically simple IT automation system. 
    It handles configuration-management, application deployment, cloud provisioning, 
    ad-hoc task-execution, and multinode orchestration -- including trivializing things 
    like zero-downtime rolling updates with load balancers.
    
grade: stable 
confinement: devmode 
base: core20

architectures:
  - build-on: amd64
    run-on: [amd64, armhf, arm64, ppc64el, s390x]   

plugs:
  ansible:
    interface: personal-files
    write:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
    read:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
  ansible:
    interface: personal-files
    read:
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT
  ansible:
    interface: personal-files
    read:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT       
    write:
      - $HOME/.ansible/roles
      - $HOME/$SNAP_USER_COMMON
      - $HOME/$SNAP_USER_CURRENT      

apps:
  ansible:
    command: bin/ansible
  ansible:
    command: bin/ansible-playbook
  ansible-galaxy:
    command: bin/ansible-galaxy
  ansible-config:
    command: bin/ansible-config
  ansible-connection:
    command: bin/ansible-connection
  ansible-console:
    command: bin/ansible-console
  ansible-doc:
    command: bin/ansible-doc
  ansible-inventory:
    command: bin/ansible-inventory
  ansible-pull:
    command: bin/ansible-pull
  ansible-vault:
    command: bin/ansible-vault  
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - mount-observe
      - system-files
      - personal-files
     
parts: 
  ansible:
    source: https://github.com/ansible/ansible/tree/stable-2.12
    source-type: git
    plugin: python
    requirements: [requirements.txt]
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - python3
      
    stage-packages:
      - python3
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography
