name: ansible
adopt-info: ansible
summary: Ansible is a radically simple IT automation system.
description: |
    Ansible is a radically simple IT automation system. 
    It handles configuration-management, application deployment, cloud provisioning, 
    ad-hoc task-execution, and multinode orchestration -- including trivializing things 
    like zero-downtime rolling updates with load balancers.
    
grade: stable 
confinement: classic
base: core20

package-repositories:
 - type: apt
   ppa: deadsnakes/ppa

apps:
  ansible: 
    command: $SNAP/.local/bin/ansible-core
    environment: 
      LC_ALL: C.UTF-8
      
parts: 
  ansible:
    source: https://github.com/ansible/ansible
    source-type: git
    source-branch: stable-2.11
    plugin: python
    requirements: [requirements.txt]
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin/
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      pipx install --include-deps ansible-core==2.11
      pipx ensurepath
      
    build-packages:
      - python3.11
      - python3-pip
      - pipx
      - python3.11-venv
      - software-properties-common
      
    stage-packages:
      - python3.11
      - python3-pip      
      - software-properties-common
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography
      - python3-jmespath

